# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(866, 634)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Button_Send = QtGui.QCommandLinkButton(self.centralwidget)
        self.Button_Send.setGeometry(QtCore.QRect(220, 450, 81, 41))
        self.Button_Send.setStyleSheet(_fromUtf8(""))
        self.Button_Send.setObjectName(_fromUtf8("Button_Send"))
        self.lineEdit_Param1 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Param1.setGeometry(QtCore.QRect(10, 400, 113, 23))
        self.lineEdit_Param1.setText(_fromUtf8(""))
        self.lineEdit_Param1.setObjectName(_fromUtf8("lineEdit_Param1"))
        self.lineEdit_Param2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Param2.setGeometry(QtCore.QRect(140, 400, 113, 23))
        self.lineEdit_Param2.setText(_fromUtf8(""))
        self.lineEdit_Param2.setObjectName(_fromUtf8("lineEdit_Param2"))
        self.lineEdit_Param3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Param3.setGeometry(QtCore.QRect(270, 400, 113, 23))
        self.lineEdit_Param3.setText(_fromUtf8(""))
        self.lineEdit_Param3.setObjectName(_fromUtf8("lineEdit_Param3"))
        self.lineEdit_Param4 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Param4.setGeometry(QtCore.QRect(400, 400, 113, 23))
        self.lineEdit_Param4.setText(_fromUtf8(""))
        self.lineEdit_Param4.setObjectName(_fromUtf8("lineEdit_Param4"))
        self.comboBox_Command = QtGui.QComboBox(self.centralwidget)
        self.comboBox_Command.setGeometry(QtCore.QRect(220, 290, 79, 23))
        self.comboBox_Command.setObjectName(_fromUtf8("comboBox_Command"))
        self.comboBox_Command.addItem(_fromUtf8(""))
        self.comboBox_Command.addItem(_fromUtf8(""))
        self.comboBox_Command.addItem(_fromUtf8(""))
        self.comboBox_Command.addItem(_fromUtf8(""))
        self.comboBox_Command.addItem(_fromUtf8(""))
        self.comboBox_Command.addItem(_fromUtf8(""))
        self.comboBox_Command.addItem(_fromUtf8(""))
        self.comboBox_Command.addItem(_fromUtf8(""))
        self.comboBox_Command.addItem(_fromUtf8(""))
        self.comboBox_Command.addItem(_fromUtf8(""))
        self.comboBox_Command.addItem(_fromUtf8(""))
        self.comboBox_Command.addItem(_fromUtf8(""))
        self.comboBox_Command.addItem(_fromUtf8(""))
        self.label_Param1 = QtGui.QLabel(self.centralwidget)
        self.label_Param1.setGeometry(QtCore.QRect(20, 370, 101, 21))
        self.label_Param1.setTextFormat(QtCore.Qt.AutoText)
        self.label_Param1.setObjectName(_fromUtf8("label_Param1"))
        self.label_Param2 = QtGui.QLabel(self.centralwidget)
        self.label_Param2.setGeometry(QtCore.QRect(150, 370, 101, 21))
        self.label_Param2.setTextFormat(QtCore.Qt.AutoText)
        self.label_Param2.setObjectName(_fromUtf8("label_Param2"))
        self.label_Param3 = QtGui.QLabel(self.centralwidget)
        self.label_Param3.setGeometry(QtCore.QRect(280, 370, 101, 21))
        self.label_Param3.setTextFormat(QtCore.Qt.AutoText)
        self.label_Param3.setObjectName(_fromUtf8("label_Param3"))
        self.label_Param4 = QtGui.QLabel(self.centralwidget)
        self.label_Param4.setGeometry(QtCore.QRect(410, 370, 101, 21))
        self.label_Param4.setTextFormat(QtCore.Qt.AutoText)
        self.label_Param4.setObjectName(_fromUtf8("label_Param4"))
        self.label_Message_received = QtGui.QLabel(self.centralwidget)
        self.label_Message_received.setGeometry(QtCore.QRect(600, 260, 181, 31))
        self.label_Message_received.setStyleSheet(_fromUtf8("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.495 rgba(255, 255, 255, 255), stop:0.505 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));"))
        self.label_Message_received.setTextFormat(QtCore.Qt.AutoText)
        self.label_Message_received.setObjectName(_fromUtf8("label_Message_received"))
        self.Button_Mission = QtGui.QPushButton(self.centralwidget)
        self.Button_Mission.setGeometry(QtCore.QRect(80, 540, 80, 23))
        self.Button_Mission.setObjectName(_fromUtf8("Button_Mission"))
        self.Button_Socket = QtGui.QPushButton(self.centralwidget)
        self.Button_Socket.setGeometry(QtCore.QRect(690, 530, 121, 41))
        self.Button_Socket.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);\n"
"font: 12pt \"Sans Serif\";\n"
""))
        self.Button_Socket.setObjectName(_fromUtf8("Button_Socket"))
        self.horizontalSlider_Mode = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider_Mode.setGeometry(QtCore.QRect(80, 180, 211, 41))
        self.horizontalSlider_Mode.setMaximum(4)
        self.horizontalSlider_Mode.setSingleStep(1)
        self.horizontalSlider_Mode.setPageStep(10)
        self.horizontalSlider_Mode.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Mode.setTickInterval(4)
        self.horizontalSlider_Mode.setObjectName(_fromUtf8("horizontalSlider_Mode"))
        self.label_ModeBrowser = QtGui.QLabel(self.centralwidget)
        self.label_ModeBrowser.setGeometry(QtCore.QRect(160, 170, 121, 16))
        self.label_ModeBrowser.setObjectName(_fromUtf8("label_ModeBrowser"))
        self.radioButton_Arm = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_Arm.setGeometry(QtCore.QRect(670, 170, 100, 21))
        self.radioButton_Arm.setObjectName(_fromUtf8("radioButton_Arm"))
        self.radioButton_Disarm = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_Disarm.setGeometry(QtCore.QRect(670, 190, 100, 21))
        self.radioButton_Disarm.setObjectName(_fromUtf8("radioButton_Disarm"))
        self.label_Title = QtGui.QLabel(self.centralwidget)
        self.label_Title.setGeometry(QtCore.QRect(240, 40, 401, 41))
        self.label_Title.setStyleSheet(_fromUtf8("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.495 rgba(255, 255, 255, 255), stop:0.505 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));"))
        self.label_Title.setTextFormat(QtCore.Qt.AutoText)
        self.label_Title.setObjectName(_fromUtf8("label_Title"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 230, 871, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 100, 871, 16))
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_Arm_Disarm = QtGui.QLabel(self.centralwidget)
        self.label_Arm_Disarm.setGeometry(QtCore.QRect(670, 140, 181, 16))
        self.label_Arm_Disarm.setObjectName(_fromUtf8("label_Arm_Disarm"))
        self.label_Mode = QtGui.QLabel(self.centralwidget)
        self.label_Mode.setGeometry(QtCore.QRect(50, 140, 321, 16))
        self.label_Mode.setObjectName(_fromUtf8("label_Mode"))
        self.logo = QtGui.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(770, 0, 81, 101))
        self.logo.setText(_fromUtf8(""))
        self.logo.setPixmap(QtGui.QPixmap(_fromUtf8(":/ex/logo.jpg")))
        self.logo.setScaledContents(True)
        self.logo.setObjectName(_fromUtf8("logo"))
        self.label_Parameter = QtGui.QLabel(self.centralwidget)
        self.label_Parameter.setGeometry(QtCore.QRect(10, 320, 201, 21))
        self.label_Parameter.setObjectName(_fromUtf8("label_Parameter"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(-10, 490, 881, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_Mission = QtGui.QLabel(self.centralwidget)
        self.label_Mission.setGeometry(QtCore.QRect(40, 510, 211, 16))
        self.label_Mission.setObjectName(_fromUtf8("label_Mission"))
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(550, 300, 301, 171))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.label_Command = QtGui.QLabel(self.centralwidget)
        self.label_Command.setGeometry(QtCore.QRect(100, 260, 351, 16))
        self.label_Command.setObjectName(_fromUtf8("label_Command"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(520, 240, 20, 261))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.Button_Isarmable = QtGui.QPushButton(self.centralwidget)
        self.Button_Isarmable.setGeometry(QtCore.QRect(450, 180, 91, 21))
        self.Button_Isarmable.setObjectName(_fromUtf8("Button_Isarmable"))
        self.label_Isarmable = QtGui.QLabel(self.centralwidget)
        self.label_Isarmable.setGeometry(QtCore.QRect(390, 140, 221, 20))
        self.label_Isarmable.setObjectName(_fromUtf8("label_Isarmable"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 866, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Interface", None))
        self.Button_Send.setText(_translate("MainWindow", "SEND", None))
        self.comboBox_Command.setItemText(0, _translate("MainWindow", "info", None))
        self.comboBox_Command.setItemText(1, _translate("MainWindow", "mode", None))
        self.comboBox_Command.setItemText(2, _translate("MainWindow", "arm", None))
        self.comboBox_Command.setItemText(3, _translate("MainWindow", "home", None))
        self.comboBox_Command.setItemText(4, _translate("MainWindow", "land", None))
        self.comboBox_Command.setItemText(5, _translate("MainWindow", "takeoff", None))
        self.comboBox_Command.setItemText(6, _translate("MainWindow", "alt", None))
        self.comboBox_Command.setItemText(7, _translate("MainWindow", "x", None))
        self.comboBox_Command.setItemText(8, _translate("MainWindow", "y", None))
        self.comboBox_Command.setItemText(9, _translate("MainWindow", "yaw", None))
        self.comboBox_Command.setItemText(10, _translate("MainWindow", "airspeed", None))
        self.comboBox_Command.setItemText(11, _translate("MainWindow", "vel", None))
        self.comboBox_Command.setItemText(12, _translate("MainWindow", "go", None))
        self.label_Param1.setText(_translate("MainWindow", "Param1", None))
        self.label_Param2.setText(_translate("MainWindow", "Param2", None))
        self.label_Param3.setText(_translate("MainWindow", "Param3", None))
        self.label_Param4.setText(_translate("MainWindow", "Param4", None))
        self.label_Message_received.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#00007f;\">Message received</span></p></body></html>", None))
        self.Button_Mission.setText(_translate("MainWindow", "Mission", None))
        self.Button_Socket.setText(_translate("MainWindow", "Close Socket", None))
        self.label_ModeBrowser.setText(_translate("MainWindow", "MODE", None))
        self.radioButton_Arm.setText(_translate("MainWindow", "Arm ", None))
        self.radioButton_Disarm.setText(_translate("MainWindow", "Disarm", None))
        self.label_Title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#000000;\">Interface for Pixhawk4 control </span></p></body></html>", None))
        self.label_Arm_Disarm.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic; color:#00007f;\">ARM/DISARM THE VEHICLE</span></p></body></html>", None))
        self.label_Mode.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic; color:#00007f;\">CHANGE THE FLIGHT MODE OF THE VEHICLE</span></p></body></html>", None))
        self.label_Parameter.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">0 parameter :</span></p></body></html>", None))
        self.label_Mission.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic; color:#00007f;\">CLICK TO LAUNCH THE MISSION</span></p></body></html>", None))
        self.label_Command.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic; color:#00007f;\">SELECT THE COMMAND, ENTER PARAMETERS AND SEND</span></p></body></html>", None))
        self.Button_Isarmable.setText(_translate("MainWindow", "is_armable?", None))
        self.label_Isarmable.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic; color:#00007f;\">CHECK IF THE VEHICLE IS ARMABLE</span></p></body></html>", None))

import logo_rc
